version: 0.1

phases:
  install:
    commands:
      - echo installing
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
      - sudo apt-get install nodejs
      - sudo apt-get install npm
  build:
    commands:
      - echo $PATH
      - nodejs -v
      - ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner
      - ls -al
artifacts:
  files:
    - '**/*'
