version: 0.2

phases:
  install:
    commands:
      - echo installing
      - printenv
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
      - apt-get install jq -y
  build:
    commands:
      - echo $PATH
      - sonar-scanner #./sonar-scanner-3.3.0.1492-linux/bin/
      - ls -al
      #- chmod a+x checksonar.sh
      #- ./checksonar.sh
      - export TESTKK="ERROR" #"$(curl -s -u 716cb3fe910a6b045112c469b81ff08f712b1ec0: https://sonarcloud.io/api/qualitygates/project_status?projectKey=testphp1 | jq '.projectStatus.status')" #"ERROR"
      - if expr "$TESTKK" == "ERROR" ; then exit 1; fi
  #post_build:
    #commands:
artifacts:
  files:
    - '**/*'
